services:
  database_server:
    image: mcr.microsoft.com/mssql/server
    env_file:
      - .env
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
    volumes:
      - data-volume:/var/opt/mssql

  web_server:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: dockerfile-webserver
    env_file:
      - .env
    depends_on:
      - database_server
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./app:/app
      - ./setup:/setup
    entrypoint: [ "sh", "/setup/bootstrap.sh" ]
    mem_limit: 512m

  webpack:
    build:
      context: .
      dockerfile: dockerfile-webpack
    command: ["webpack", "--config", "webpack.config.js", "--watch"]
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - web_server

volumes:
  data-volume:
